version: '3.8'

services:
  # Laravel Backend
  backend:
    build:
      context: ./docker/backend
    container_name: petstore_backend
    restart: unless-stopped
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    volumes:
      - ./backend:/var/www/html
    networks:
      - laravel
    depends_on:
      - nginx

  # Nginx
  nginx:
    image: nginx:1.25
    container_name: petstore_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/backend/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
